import Link from "next/link";
import Header from "./components/Header";
import "./globals.css";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import BlogPromo from "./components/BlogPromo";

export const metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-denim bg-repeat text-white">
        <Header />
        <div className="max-w-2xl sm:mt-10 mt-4 mx-auto px-5">
          <Hero />
        </div>
      </body>
      <BlogPromo />
      <Footer />
    </html>
  );
}
